# Site settings
title: kevin olega
tag_text: kevin olega
description: kevin olega homepage
url: "http://kevinolega.com"
baseurl:

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
